</$objtype/mkfile

LIB=/$objtype/lib/libthread.a

# the machine's part: $objtype.c, main.c, sched.c - wasm32's own in wasm32/
# (contexts, not longjmp; no fork of the stack)
MACHOFILES=`{if(~ $objtype wasm32) echo wasm32.$O wasm32main.$O wasm32sched.$O; if not echo $objtype.$O main.$O sched.$O}

OFILES=\
	$MACHOFILES\
	channel.$O\
	chanprint.$O\
	create.$O\
	debug.$O\
	exec.$O\
	exit.$O\
	id.$O\
	iocall.$O\
	ioclose.$O\
	iodial.$O\
	ioopen.$O\
	ioproc.$O\
	ioread.$O\
	ioreadn.$O\
	iosleep.$O\
	iowrite.$O\
	ioflush.$O\
	kill.$O\
	lib.$O\
	note.$O\
	ref.$O\
	rendez.$O\

CFILES=\
	386.c\
	amd64.c\
	arm.c\
	channel.c\
	chanprint.c\
	create.c\
	debug.c\
	dial.c\
	example.c\
	exec.c\
	exit.c\
	id.c\
	iocall.c\
	ioclose.c\
	iodial.c\
	ioopen.c\
	ioproc.c\
	ioread.c\
	ioreadn.c\
	iowrite.c\
	kill.c\
	lib.c\
	main.c\
	mips.c\
	note.c\
	power.c\
	rendez.c\
	sched.c\
	test.c\
	tprimes.c\

HFILES=\
	/sys/include/thread.h\
	threadimpl.h\

all:V:	$LIB sched.$objtype.acid channel.$objtype.acid

spim.$O:	mips.c
	$CC $CFLAGS -o $target mips.c

wasm32.$O:	wasm32/wasm32.c
	$CC $CFLAGS -I. -o $target wasm32/wasm32.c
wasm32main.$O:	wasm32/main.c
	$CC $CFLAGS -I. -o $target wasm32/main.c
wasm32sched.$O:	wasm32/sched.c
	$CC $CFLAGS -I. -o $target wasm32/sched.c

</sys/src/cmd/mksyslib

$O.tprimes: tprimes.$O $LIB
	$LD -o $target $prereq
